services:

  autohttps:
    image: cruizba/autohttps:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
    environment:
      - SERVICES=random-cats:80,random-dogs:80
    depends_on:
      - random-cats
      - random-dogs

  random-cats:
    build:
      context: ./example-apps/random-cats
      dockerfile: Dockerfile

  random-dogs:
    build:
      context: ./example-apps/random-dogs
      dockerfile: Dockerfile
